### ISSUE TITLE
fixing bootstrap3-horizontal

### ISSUE THREAD

**Issue by yayitswei** [jkk/formative#64]
Thanks for making formative! I've found it very useful so far.

I noticed the `bootstrap3-horizontal` form is broken. What would it take to fix it?

```
;; Broken
#_(defmethod render-form :bootstrap3-horizontal [form-attrs fields opts]
   (render-bootstrap-form form-attrs fields "form-shell form-horizontal" opts))
```

I'm using the latest version of Bootstrap, and the stacked layout doesn't look appropriate for desktop window sizes.

**Comment by iku000888** [comment]
Hey @yayitswei ! Thanks for the issue.

Must admit that I have never used `bootstrap3-horizontal` :sweat_drops: 

Anyhow having that said, form renderers are just pluggable multimethods and provided bootstrap3 is really getting old and you are using the latest greatest bootstrap(4?), best route is to write a new render-form that works well with the latest bootstrap. (plus no work has been done to support latest bootstrap anyways)

I am also fine resurrecting the commented out code because it will not break anything, but not sure what is inside. :man_shrugging:

**Comment by yayitswei** [comment]
I see, I'll try out the commented code and if that doesn't do it, I'll try writing my own renderer. If it ends up being pluggable perhaps I'll issue a PR. Thanks!
